// flow-typed signature: 7b9533d6452c48300cc297bac4b0bdd7
// flow-typed version: <<STUB>>/@vx/boxplot_v^0.0.136/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/boxplot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/boxplot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/boxplot/build/boxplots/BoxPlot' {
  declare module.exports: any;
}

declare module '@vx/boxplot/build/index' {
  declare module.exports: any;
}

declare module '@vx/boxplot/build/util/additionalProps' {
  declare module.exports: any;
}

declare module '@vx/boxplot/build/util/callOrValue' {
  declare module.exports: any;
}

declare module '@vx/boxplot/src/boxplots/BoxPlot' {
  declare module.exports: any;
}

declare module '@vx/boxplot/src/index' {
  declare module.exports: any;
}

declare module '@vx/boxplot/src/util/additionalProps' {
  declare module.exports: any;
}

declare module '@vx/boxplot/src/util/callOrValue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/boxplot/build/boxplots/BoxPlot.js' {
  declare module.exports: $Exports<'@vx/boxplot/build/boxplots/BoxPlot'>;
}
declare module '@vx/boxplot/build/index.js' {
  declare module.exports: $Exports<'@vx/boxplot/build/index'>;
}
declare module '@vx/boxplot/build/util/additionalProps.js' {
  declare module.exports: $Exports<'@vx/boxplot/build/util/additionalProps'>;
}
declare module '@vx/boxplot/build/util/callOrValue.js' {
  declare module.exports: $Exports<'@vx/boxplot/build/util/callOrValue'>;
}
declare module '@vx/boxplot/src/boxplots/BoxPlot.js' {
  declare module.exports: $Exports<'@vx/boxplot/src/boxplots/BoxPlot'>;
}
declare module '@vx/boxplot/src/index.js' {
  declare module.exports: $Exports<'@vx/boxplot/src/index'>;
}
declare module '@vx/boxplot/src/util/additionalProps.js' {
  declare module.exports: $Exports<'@vx/boxplot/src/util/additionalProps'>;
}
declare module '@vx/boxplot/src/util/callOrValue.js' {
  declare module.exports: $Exports<'@vx/boxplot/src/util/callOrValue'>;
}
