// flow-typed signature: bb5571bb9f1aa9c041c34238eaf868f4
// flow-typed version: <<STUB>>/@vx/event_v^0.0.136/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/event/build/index' {
  declare module.exports: any;
}

declare module '@vx/event/build/localPoint' {
  declare module.exports: any;
}

declare module '@vx/event/build/touchPoint' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/event/build/index.js' {
  declare module.exports: $Exports<'@vx/event/build/index'>;
}
declare module '@vx/event/build/localPoint.js' {
  declare module.exports: $Exports<'@vx/event/build/localPoint'>;
}
declare module '@vx/event/build/touchPoint.js' {
  declare module.exports: $Exports<'@vx/event/build/touchPoint'>;
}
