// flow-typed signature: 41f2af79e1e69d9a592b3821bed3d909
// flow-typed version: <<STUB>>/@vx/heatmap_v^0.0.136/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/heatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/heatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/heatmap/build/heatmaps/circle' {
  declare module.exports: any;
}

declare module '@vx/heatmap/build/heatmaps/heatmap' {
  declare module.exports: any;
}

declare module '@vx/heatmap/build/heatmaps/rect' {
  declare module.exports: any;
}

declare module '@vx/heatmap/build/index' {
  declare module.exports: any;
}

declare module '@vx/heatmap/build/util/additionalProps' {
  declare module.exports: any;
}

declare module '@vx/heatmap/build/util/callOrValue' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/heatmap/build/heatmaps/circle.js' {
  declare module.exports: $Exports<'@vx/heatmap/build/heatmaps/circle'>;
}
declare module '@vx/heatmap/build/heatmaps/heatmap.js' {
  declare module.exports: $Exports<'@vx/heatmap/build/heatmaps/heatmap'>;
}
declare module '@vx/heatmap/build/heatmaps/rect.js' {
  declare module.exports: $Exports<'@vx/heatmap/build/heatmaps/rect'>;
}
declare module '@vx/heatmap/build/index.js' {
  declare module.exports: $Exports<'@vx/heatmap/build/index'>;
}
declare module '@vx/heatmap/build/util/additionalProps.js' {
  declare module.exports: $Exports<'@vx/heatmap/build/util/additionalProps'>;
}
declare module '@vx/heatmap/build/util/callOrValue.js' {
  declare module.exports: $Exports<'@vx/heatmap/build/util/callOrValue'>;
}
