// flow-typed signature: 63f58810f52cb20714866ea732193c9d
// flow-typed version: <<STUB>>/@vx/mock-data_v^0.0.136/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/mock-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/mock-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/mock-data/build/generators/genBin' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/generators/genBins' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/generators/genBoxPlot' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/generators/genDateValue' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/generators/genRandomNormalPoints' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/index' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/appleStock' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/bitcoinPrice' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/browserUsage' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/cityTemperature' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/groupDateValue' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/lesMiserables' {
  declare module.exports: any;
}

declare module '@vx/mock-data/build/mocks/letterFrequency' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/mock-data/build/generators/genBin.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/generators/genBin'>;
}
declare module '@vx/mock-data/build/generators/genBins.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/generators/genBins'>;
}
declare module '@vx/mock-data/build/generators/genBoxPlot.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/generators/genBoxPlot'>;
}
declare module '@vx/mock-data/build/generators/genDateValue.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/generators/genDateValue'>;
}
declare module '@vx/mock-data/build/generators/genRandomNormalPoints.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/generators/genRandomNormalPoints'>;
}
declare module '@vx/mock-data/build/index.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/index'>;
}
declare module '@vx/mock-data/build/mocks/appleStock.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/appleStock'>;
}
declare module '@vx/mock-data/build/mocks/bitcoinPrice.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/bitcoinPrice'>;
}
declare module '@vx/mock-data/build/mocks/browserUsage.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/browserUsage'>;
}
declare module '@vx/mock-data/build/mocks/cityTemperature.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/cityTemperature'>;
}
declare module '@vx/mock-data/build/mocks/groupDateValue.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/groupDateValue'>;
}
declare module '@vx/mock-data/build/mocks/lesMiserables.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/lesMiserables'>;
}
declare module '@vx/mock-data/build/mocks/letterFrequency.js' {
  declare module.exports: $Exports<'@vx/mock-data/build/mocks/letterFrequency'>;
}
