// flow-typed signature: 1454bdcd05156b539aa231d973b4308f
// flow-typed version: <<STUB>>/@vx/shape_v^0.0.139/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/shape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/shape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/shape/build/index' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/Arc' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/AreaClosed' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/AreaStack' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/Bar' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/BarGroup' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/BarStack' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/Line' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/LinePath' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/LineRadial' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/LinkHorizontal' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/LinkRadial' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/LinkVertical' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/Stack' {
  declare module.exports: any;
}

declare module '@vx/shape/build/shapes/Streamgraph' {
  declare module.exports: any;
}

declare module '@vx/shape/build/util/additionalProps' {
  declare module.exports: any;
}

declare module '@vx/shape/build/util/callOrValue' {
  declare module.exports: any;
}

declare module '@vx/shape/build/util/stackOffset' {
  declare module.exports: any;
}

declare module '@vx/shape/build/util/stackOrder' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/shape/build/index.js' {
  declare module.exports: $Exports<'@vx/shape/build/index'>;
}
declare module '@vx/shape/build/shapes/Arc.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/Arc'>;
}
declare module '@vx/shape/build/shapes/AreaClosed.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/AreaClosed'>;
}
declare module '@vx/shape/build/shapes/AreaStack.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/AreaStack'>;
}
declare module '@vx/shape/build/shapes/Bar.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/Bar'>;
}
declare module '@vx/shape/build/shapes/BarGroup.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/BarGroup'>;
}
declare module '@vx/shape/build/shapes/BarStack.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/BarStack'>;
}
declare module '@vx/shape/build/shapes/Line.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/Line'>;
}
declare module '@vx/shape/build/shapes/LinePath.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/LinePath'>;
}
declare module '@vx/shape/build/shapes/LineRadial.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/LineRadial'>;
}
declare module '@vx/shape/build/shapes/LinkHorizontal.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/LinkHorizontal'>;
}
declare module '@vx/shape/build/shapes/LinkRadial.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/LinkRadial'>;
}
declare module '@vx/shape/build/shapes/LinkVertical.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/LinkVertical'>;
}
declare module '@vx/shape/build/shapes/Stack.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/Stack'>;
}
declare module '@vx/shape/build/shapes/Streamgraph.js' {
  declare module.exports: $Exports<'@vx/shape/build/shapes/Streamgraph'>;
}
declare module '@vx/shape/build/util/additionalProps.js' {
  declare module.exports: $Exports<'@vx/shape/build/util/additionalProps'>;
}
declare module '@vx/shape/build/util/callOrValue.js' {
  declare module.exports: $Exports<'@vx/shape/build/util/callOrValue'>;
}
declare module '@vx/shape/build/util/stackOffset.js' {
  declare module.exports: $Exports<'@vx/shape/build/util/stackOffset'>;
}
declare module '@vx/shape/build/util/stackOrder.js' {
  declare module.exports: $Exports<'@vx/shape/build/util/stackOrder'>;
}
