// flow-typed signature: 1c5bdd5aabb08ef4e7227615e626f744
// flow-typed version: <<STUB>>/@vx/tooltip_v^0.0.137/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/tooltip/build/enhancers/withTooltip' {
  declare module.exports: any;
}

declare module '@vx/tooltip/build/index' {
  declare module.exports: any;
}

declare module '@vx/tooltip/build/tooltips/Tooltip' {
  declare module.exports: any;
}

declare module '@vx/tooltip/build/tooltips/TooltipWithBounds' {
  declare module.exports: any;
}

declare module '@vx/tooltip/src/enhancers/withTooltip' {
  declare module.exports: any;
}

declare module '@vx/tooltip/src/index' {
  declare module.exports: any;
}

declare module '@vx/tooltip/src/tooltips/Tooltip' {
  declare module.exports: any;
}

declare module '@vx/tooltip/src/tooltips/TooltipWithBounds' {
  declare module.exports: any;
}

declare module '@vx/tooltip/test/Tooltip.test' {
  declare module.exports: any;
}

declare module '@vx/tooltip/test/TooltipWithBounds.test' {
  declare module.exports: any;
}

declare module '@vx/tooltip/test/withTooltip.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/tooltip/build/enhancers/withTooltip.js' {
  declare module.exports: $Exports<'@vx/tooltip/build/enhancers/withTooltip'>;
}
declare module '@vx/tooltip/build/index.js' {
  declare module.exports: $Exports<'@vx/tooltip/build/index'>;
}
declare module '@vx/tooltip/build/tooltips/Tooltip.js' {
  declare module.exports: $Exports<'@vx/tooltip/build/tooltips/Tooltip'>;
}
declare module '@vx/tooltip/build/tooltips/TooltipWithBounds.js' {
  declare module.exports: $Exports<'@vx/tooltip/build/tooltips/TooltipWithBounds'>;
}
declare module '@vx/tooltip/src/enhancers/withTooltip.js' {
  declare module.exports: $Exports<'@vx/tooltip/src/enhancers/withTooltip'>;
}
declare module '@vx/tooltip/src/index.js' {
  declare module.exports: $Exports<'@vx/tooltip/src/index'>;
}
declare module '@vx/tooltip/src/tooltips/Tooltip.js' {
  declare module.exports: $Exports<'@vx/tooltip/src/tooltips/Tooltip'>;
}
declare module '@vx/tooltip/src/tooltips/TooltipWithBounds.js' {
  declare module.exports: $Exports<'@vx/tooltip/src/tooltips/TooltipWithBounds'>;
}
declare module '@vx/tooltip/test/Tooltip.test.js' {
  declare module.exports: $Exports<'@vx/tooltip/test/Tooltip.test'>;
}
declare module '@vx/tooltip/test/TooltipWithBounds.test.js' {
  declare module.exports: $Exports<'@vx/tooltip/test/TooltipWithBounds.test'>;
}
declare module '@vx/tooltip/test/withTooltip.test.js' {
  declare module.exports: $Exports<'@vx/tooltip/test/withTooltip.test'>;
}
