// flow-typed signature: 78968b57ef170b2ed9728a8cc4a25d4c
// flow-typed version: <<STUB>>/payment_v^2.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'payment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'payment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'payment/dist/payment' {
  declare module.exports: any;
}

declare module 'payment/karma.conf' {
  declare module.exports: any;
}

declare module 'payment/lib/index' {
  declare module.exports: any;
}

declare module 'payment/tests.bundle' {
  declare module.exports: any;
}

declare module 'payment/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'payment/dist/payment.js' {
  declare module.exports: $Exports<'payment/dist/payment'>;
}
declare module 'payment/karma.conf.js' {
  declare module.exports: $Exports<'payment/karma.conf'>;
}
declare module 'payment/lib/index.js' {
  declare module.exports: $Exports<'payment/lib/index'>;
}
declare module 'payment/tests.bundle.js' {
  declare module.exports: $Exports<'payment/tests.bundle'>;
}
declare module 'payment/webpack.config.js' {
  declare module.exports: $Exports<'payment/webpack.config'>;
}
