// flow-typed signature: fd2aa9c5ef93f223e5b62f4c4328b63e
// flow-typed version: <<STUB>>/react-scroll-box_v^0.2.9/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-box'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-box' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll-box/src/main/GenericScrollBox' {
  declare module.exports: any;
}

declare module 'react-scroll-box/src/main/index' {
  declare module.exports: any;
}

declare module 'react-scroll-box/src/main/ScrollBox' {
  declare module.exports: any;
}

declare module 'react-scroll-box/target/out/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll-box/src/main/GenericScrollBox.js' {
  declare module.exports: $Exports<'react-scroll-box/src/main/GenericScrollBox'>;
}
declare module 'react-scroll-box/src/main/index.js' {
  declare module.exports: $Exports<'react-scroll-box/src/main/index'>;
}
declare module 'react-scroll-box/src/main/ScrollBox.js' {
  declare module.exports: $Exports<'react-scroll-box/src/main/ScrollBox'>;
}
declare module 'react-scroll-box/target/out/index.js' {
  declare module.exports: $Exports<'react-scroll-box/target/out/index'>;
}
