// flow-typed signature: 8396959bc6fe0f434fab23d7481cd77d
// flow-typed version: <<STUB>>/react-idle_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-idle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-idle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-idle/es/index' {
  declare module.exports: any;
}

declare module 'react-idle/lib/index' {
  declare module.exports: any;
}

declare module 'react-idle/umd/react-idle' {
  declare module.exports: any;
}

declare module 'react-idle/umd/react-idle.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-idle/es/index.js' {
  declare module.exports: $Exports<'react-idle/es/index'>;
}
declare module 'react-idle/lib/index.js' {
  declare module.exports: $Exports<'react-idle/lib/index'>;
}
declare module 'react-idle/umd/react-idle.js' {
  declare module.exports: $Exports<'react-idle/umd/react-idle'>;
}
declare module 'react-idle/umd/react-idle.min.js' {
  declare module.exports: $Exports<'react-idle/umd/react-idle.min'>;
}
