// flow-typed signature: f8361093a7f9b0fd57c0cccb12a9d558
// flow-typed version: <<STUB>>/react-popover_v^0.4.16/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-popover'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-popover' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-popover/build/index' {
  declare module.exports: any;
}

declare module 'react-popover/build/layout' {
  declare module.exports: any;
}

declare module 'react-popover/build/on-resize' {
  declare module.exports: any;
}

declare module 'react-popover/build/platform' {
  declare module.exports: any;
}

declare module 'react-popover/build/react-layer-mixin' {
  declare module.exports: any;
}

declare module 'react-popover/build/tip' {
  declare module.exports: any;
}

declare module 'react-popover/build/utils' {
  declare module.exports: any;
}

declare module 'react-popover/examples/jsx/main' {
  declare module.exports: any;
}

declare module 'react-popover/examples/playground/main' {
  declare module.exports: any;
}

declare module 'react-popover/examples/rows/main' {
  declare module.exports: any;
}

declare module 'react-popover/lib/index' {
  declare module.exports: any;
}

declare module 'react-popover/lib/layout' {
  declare module.exports: any;
}

declare module 'react-popover/lib/on-resize' {
  declare module.exports: any;
}

declare module 'react-popover/lib/platform' {
  declare module.exports: any;
}

declare module 'react-popover/lib/react-layer-mixin' {
  declare module.exports: any;
}

declare module 'react-popover/lib/tip' {
  declare module.exports: any;
}

declare module 'react-popover/lib/utils' {
  declare module.exports: any;
}

declare module 'react-popover/test/index.spec' {
  declare module.exports: any;
}

declare module 'react-popover/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-popover/build/index.js' {
  declare module.exports: $Exports<'react-popover/build/index'>;
}
declare module 'react-popover/build/layout.js' {
  declare module.exports: $Exports<'react-popover/build/layout'>;
}
declare module 'react-popover/build/on-resize.js' {
  declare module.exports: $Exports<'react-popover/build/on-resize'>;
}
declare module 'react-popover/build/platform.js' {
  declare module.exports: $Exports<'react-popover/build/platform'>;
}
declare module 'react-popover/build/react-layer-mixin.js' {
  declare module.exports: $Exports<'react-popover/build/react-layer-mixin'>;
}
declare module 'react-popover/build/tip.js' {
  declare module.exports: $Exports<'react-popover/build/tip'>;
}
declare module 'react-popover/build/utils.js' {
  declare module.exports: $Exports<'react-popover/build/utils'>;
}
declare module 'react-popover/examples/jsx/main.js' {
  declare module.exports: $Exports<'react-popover/examples/jsx/main'>;
}
declare module 'react-popover/examples/playground/main.js' {
  declare module.exports: $Exports<'react-popover/examples/playground/main'>;
}
declare module 'react-popover/examples/rows/main.js' {
  declare module.exports: $Exports<'react-popover/examples/rows/main'>;
}
declare module 'react-popover/lib/index.js' {
  declare module.exports: $Exports<'react-popover/lib/index'>;
}
declare module 'react-popover/lib/layout.js' {
  declare module.exports: $Exports<'react-popover/lib/layout'>;
}
declare module 'react-popover/lib/on-resize.js' {
  declare module.exports: $Exports<'react-popover/lib/on-resize'>;
}
declare module 'react-popover/lib/platform.js' {
  declare module.exports: $Exports<'react-popover/lib/platform'>;
}
declare module 'react-popover/lib/react-layer-mixin.js' {
  declare module.exports: $Exports<'react-popover/lib/react-layer-mixin'>;
}
declare module 'react-popover/lib/tip.js' {
  declare module.exports: $Exports<'react-popover/lib/tip'>;
}
declare module 'react-popover/lib/utils.js' {
  declare module.exports: $Exports<'react-popover/lib/utils'>;
}
declare module 'react-popover/test/index.spec.js' {
  declare module.exports: $Exports<'react-popover/test/index.spec'>;
}
declare module 'react-popover/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-popover/webpack.config.babel'>;
}
