// flow-typed signature: 256384ad2d0a0be0071d7d2712a61456
// flow-typed version: <<STUB>>/react-toastify_v^2.0.0-rc.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toastify/dist/ReactToastify.min' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/config' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/DefaultCloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/index' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/toaster' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/util/EventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/util/objectValues' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/util/propValidator' {
  declare module.exports: any;
}

declare module 'react-toastify/src/config' {
  declare module.exports: any;
}

declare module 'react-toastify/src/DefaultCloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/src/index' {
  declare module.exports: any;
}

declare module 'react-toastify/src/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/src/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/src/toaster' {
  declare module.exports: any;
}

declare module 'react-toastify/src/util/EventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/src/util/objectValues' {
  declare module.exports: any;
}

declare module 'react-toastify/src/util/propValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toastify/dist/ReactToastify.min.js' {
  declare module.exports: $Exports<'react-toastify/dist/ReactToastify.min'>;
}
declare module 'react-toastify/lib/config.js' {
  declare module.exports: $Exports<'react-toastify/lib/config'>;
}
declare module 'react-toastify/lib/DefaultCloseButton.js' {
  declare module.exports: $Exports<'react-toastify/lib/DefaultCloseButton'>;
}
declare module 'react-toastify/lib/index.js' {
  declare module.exports: $Exports<'react-toastify/lib/index'>;
}
declare module 'react-toastify/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/lib/ProgressBar'>;
}
declare module 'react-toastify/lib/Toast.js' {
  declare module.exports: $Exports<'react-toastify/lib/Toast'>;
}
declare module 'react-toastify/lib/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/lib/ToastContainer'>;
}
declare module 'react-toastify/lib/toaster.js' {
  declare module.exports: $Exports<'react-toastify/lib/toaster'>;
}
declare module 'react-toastify/lib/util/EventManager.js' {
  declare module.exports: $Exports<'react-toastify/lib/util/EventManager'>;
}
declare module 'react-toastify/lib/util/objectValues.js' {
  declare module.exports: $Exports<'react-toastify/lib/util/objectValues'>;
}
declare module 'react-toastify/lib/util/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/lib/util/propValidator'>;
}
declare module 'react-toastify/src/config.js' {
  declare module.exports: $Exports<'react-toastify/src/config'>;
}
declare module 'react-toastify/src/DefaultCloseButton.js' {
  declare module.exports: $Exports<'react-toastify/src/DefaultCloseButton'>;
}
declare module 'react-toastify/src/index.js' {
  declare module.exports: $Exports<'react-toastify/src/index'>;
}
declare module 'react-toastify/src/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/src/ProgressBar'>;
}
declare module 'react-toastify/src/Toast.js' {
  declare module.exports: $Exports<'react-toastify/src/Toast'>;
}
declare module 'react-toastify/src/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/src/ToastContainer'>;
}
declare module 'react-toastify/src/toaster.js' {
  declare module.exports: $Exports<'react-toastify/src/toaster'>;
}
declare module 'react-toastify/src/util/EventManager.js' {
  declare module.exports: $Exports<'react-toastify/src/util/EventManager'>;
}
declare module 'react-toastify/src/util/objectValues.js' {
  declare module.exports: $Exports<'react-toastify/src/util/objectValues'>;
}
declare module 'react-toastify/src/util/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/src/util/propValidator'>;
}
