// flow-typed signature: b80711d0d436503946887f47251eb3e6
// flow-typed version: <<STUB>>/react-notifications_v^1.4.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-notifications/dist/react-notifications' {
  declare module.exports: any;
}

declare module 'react-notifications/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/index' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/Notification' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/NotificationContainer' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/NotificationManager' {
  declare module.exports: any;
}

declare module 'react-notifications/lib/Notifications' {
  declare module.exports: any;
}

declare module 'react-notifications/postcss.config' {
  declare module.exports: any;
}

declare module 'react-notifications/src/index' {
  declare module.exports: any;
}

declare module 'react-notifications/src/Notification' {
  declare module.exports: any;
}

declare module 'react-notifications/src/NotificationContainer' {
  declare module.exports: any;
}

declare module 'react-notifications/src/NotificationManager' {
  declare module.exports: any;
}

declare module 'react-notifications/src/Notifications' {
  declare module.exports: any;
}

declare module 'react-notifications/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-notifications/dist/react-notifications.js' {
  declare module.exports: $Exports<'react-notifications/dist/react-notifications'>;
}
declare module 'react-notifications/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-notifications/gulpfile.babel'>;
}
declare module 'react-notifications/lib/index.js' {
  declare module.exports: $Exports<'react-notifications/lib/index'>;
}
declare module 'react-notifications/lib/Notification.js' {
  declare module.exports: $Exports<'react-notifications/lib/Notification'>;
}
declare module 'react-notifications/lib/NotificationContainer.js' {
  declare module.exports: $Exports<'react-notifications/lib/NotificationContainer'>;
}
declare module 'react-notifications/lib/NotificationManager.js' {
  declare module.exports: $Exports<'react-notifications/lib/NotificationManager'>;
}
declare module 'react-notifications/lib/Notifications.js' {
  declare module.exports: $Exports<'react-notifications/lib/Notifications'>;
}
declare module 'react-notifications/postcss.config.js' {
  declare module.exports: $Exports<'react-notifications/postcss.config'>;
}
declare module 'react-notifications/src/index.js' {
  declare module.exports: $Exports<'react-notifications/src/index'>;
}
declare module 'react-notifications/src/Notification.js' {
  declare module.exports: $Exports<'react-notifications/src/Notification'>;
}
declare module 'react-notifications/src/NotificationContainer.js' {
  declare module.exports: $Exports<'react-notifications/src/NotificationContainer'>;
}
declare module 'react-notifications/src/NotificationManager.js' {
  declare module.exports: $Exports<'react-notifications/src/NotificationManager'>;
}
declare module 'react-notifications/src/Notifications.js' {
  declare module.exports: $Exports<'react-notifications/src/Notifications'>;
}
declare module 'react-notifications/webpack.config.js' {
  declare module.exports: $Exports<'react-notifications/webpack.config'>;
}
