// flow-typed signature: 80668858d18be9f4385f108dd97c7cc1
// flow-typed version: <<STUB>>/react-perfect-scrollbar_v^0.2.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-perfect-scrollbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-perfect-scrollbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-perfect-scrollbar/dist/react-perfect-scrollbar' {
  declare module.exports: any;
}

declare module 'react-perfect-scrollbar/dist/react-perfect-scrollbar.min' {
  declare module.exports: any;
}

declare module 'react-perfect-scrollbar/lib/index' {
  declare module.exports: any;
}

declare module 'react-perfect-scrollbar/lib/scrollbar' {
  declare module.exports: any;
}

declare module 'react-perfect-scrollbar/src/index' {
  declare module.exports: any;
}

declare module 'react-perfect-scrollbar/src/scrollbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-perfect-scrollbar/dist/react-perfect-scrollbar.js' {
  declare module.exports: $Exports<'react-perfect-scrollbar/dist/react-perfect-scrollbar'>;
}
declare module 'react-perfect-scrollbar/dist/react-perfect-scrollbar.min.js' {
  declare module.exports: $Exports<'react-perfect-scrollbar/dist/react-perfect-scrollbar.min'>;
}
declare module 'react-perfect-scrollbar/lib/index.js' {
  declare module.exports: $Exports<'react-perfect-scrollbar/lib/index'>;
}
declare module 'react-perfect-scrollbar/lib/scrollbar.js' {
  declare module.exports: $Exports<'react-perfect-scrollbar/lib/scrollbar'>;
}
declare module 'react-perfect-scrollbar/src/index.js' {
  declare module.exports: $Exports<'react-perfect-scrollbar/src/index'>;
}
declare module 'react-perfect-scrollbar/src/scrollbar.js' {
  declare module.exports: $Exports<'react-perfect-scrollbar/src/scrollbar'>;
}
