// flow-typed signature: 4823d3cfe33b1425e1c4c1f77ff2a243
// flow-typed version: <<STUB>>/redux-saga-thunk_v^0.5.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-thunk/dist/index' {
  declare module.exports: any;
}

declare module 'redux-saga-thunk/dist/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga-thunk/dist/reducer' {
  declare module.exports: any;
}

declare module 'redux-saga-thunk/dist/selectors' {
  declare module.exports: any;
}

declare module 'redux-saga-thunk/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-thunk/dist/index.js' {
  declare module.exports: $Exports<'redux-saga-thunk/dist/index'>;
}
declare module 'redux-saga-thunk/dist/middleware.js' {
  declare module.exports: $Exports<'redux-saga-thunk/dist/middleware'>;
}
declare module 'redux-saga-thunk/dist/reducer.js' {
  declare module.exports: $Exports<'redux-saga-thunk/dist/reducer'>;
}
declare module 'redux-saga-thunk/dist/selectors.js' {
  declare module.exports: $Exports<'redux-saga-thunk/dist/selectors'>;
}
declare module 'redux-saga-thunk/dist/utils.js' {
  declare module.exports: $Exports<'redux-saga-thunk/dist/utils'>;
}
declare module 'redux-saga-thunk/index' {
  declare module.exports: $Exports<'redux-saga-thunk'>;
}
declare module 'redux-saga-thunk/index.js' {
  declare module.exports: $Exports<'redux-saga-thunk'>;
}
