// flow-typed signature: 1acd72a912843c03870dc1ed48603b05
// flow-typed version: <<STUB>>/scriptly_v^0.0.7/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scriptly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scriptly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'scriptly/index' {
  declare module.exports: $Exports<'scriptly'>;
}
declare module 'scriptly/index.js' {
  declare module.exports: $Exports<'scriptly'>;
}
