// flow-typed signature: 948de3227a0c11fc3473a62b7bb542ef
// flow-typed version: <<STUB>>/styled-system_v^1.0.0-9/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-system/bench/index' {
  declare module.exports: any;
}

declare module 'styled-system/dist/color' {
  declare module.exports: any;
}

declare module 'styled-system/dist/constants' {
  declare module.exports: any;
}

declare module 'styled-system/dist/font-size' {
  declare module.exports: any;
}

declare module 'styled-system/dist/index' {
  declare module.exports: any;
}

declare module 'styled-system/dist/remove-props' {
  declare module.exports: any;
}

declare module 'styled-system/dist/responsive-style' {
  declare module.exports: any;
}

declare module 'styled-system/dist/space' {
  declare module.exports: any;
}

declare module 'styled-system/dist/style' {
  declare module.exports: any;
}

declare module 'styled-system/dist/util' {
  declare module.exports: any;
}

declare module 'styled-system/dist/width' {
  declare module.exports: any;
}

declare module 'styled-system/src/color' {
  declare module.exports: any;
}

declare module 'styled-system/src/constants' {
  declare module.exports: any;
}

declare module 'styled-system/src/font-size' {
  declare module.exports: any;
}

declare module 'styled-system/src/index' {
  declare module.exports: any;
}

declare module 'styled-system/src/remove-props' {
  declare module.exports: any;
}

declare module 'styled-system/src/responsive-style' {
  declare module.exports: any;
}

declare module 'styled-system/src/space' {
  declare module.exports: any;
}

declare module 'styled-system/src/style' {
  declare module.exports: any;
}

declare module 'styled-system/src/util' {
  declare module.exports: any;
}

declare module 'styled-system/src/width' {
  declare module.exports: any;
}

declare module 'styled-system/test' {
  declare module.exports: any;
}

declare module 'styled-system/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-system/bench/index.js' {
  declare module.exports: $Exports<'styled-system/bench/index'>;
}
declare module 'styled-system/dist/color.js' {
  declare module.exports: $Exports<'styled-system/dist/color'>;
}
declare module 'styled-system/dist/constants.js' {
  declare module.exports: $Exports<'styled-system/dist/constants'>;
}
declare module 'styled-system/dist/font-size.js' {
  declare module.exports: $Exports<'styled-system/dist/font-size'>;
}
declare module 'styled-system/dist/index.js' {
  declare module.exports: $Exports<'styled-system/dist/index'>;
}
declare module 'styled-system/dist/remove-props.js' {
  declare module.exports: $Exports<'styled-system/dist/remove-props'>;
}
declare module 'styled-system/dist/responsive-style.js' {
  declare module.exports: $Exports<'styled-system/dist/responsive-style'>;
}
declare module 'styled-system/dist/space.js' {
  declare module.exports: $Exports<'styled-system/dist/space'>;
}
declare module 'styled-system/dist/style.js' {
  declare module.exports: $Exports<'styled-system/dist/style'>;
}
declare module 'styled-system/dist/util.js' {
  declare module.exports: $Exports<'styled-system/dist/util'>;
}
declare module 'styled-system/dist/width.js' {
  declare module.exports: $Exports<'styled-system/dist/width'>;
}
declare module 'styled-system/src/color.js' {
  declare module.exports: $Exports<'styled-system/src/color'>;
}
declare module 'styled-system/src/constants.js' {
  declare module.exports: $Exports<'styled-system/src/constants'>;
}
declare module 'styled-system/src/font-size.js' {
  declare module.exports: $Exports<'styled-system/src/font-size'>;
}
declare module 'styled-system/src/index.js' {
  declare module.exports: $Exports<'styled-system/src/index'>;
}
declare module 'styled-system/src/remove-props.js' {
  declare module.exports: $Exports<'styled-system/src/remove-props'>;
}
declare module 'styled-system/src/responsive-style.js' {
  declare module.exports: $Exports<'styled-system/src/responsive-style'>;
}
declare module 'styled-system/src/space.js' {
  declare module.exports: $Exports<'styled-system/src/space'>;
}
declare module 'styled-system/src/style.js' {
  declare module.exports: $Exports<'styled-system/src/style'>;
}
declare module 'styled-system/src/util.js' {
  declare module.exports: $Exports<'styled-system/src/util'>;
}
declare module 'styled-system/src/width.js' {
  declare module.exports: $Exports<'styled-system/src/width'>;
}
declare module 'styled-system/test.js' {
  declare module.exports: $Exports<'styled-system/test'>;
}
declare module 'styled-system/webpack.config.js' {
  declare module.exports: $Exports<'styled-system/webpack.config'>;
}
