// flow-typed signature: 81dccf7411f7b1ef2645df9c69a37e88
// flow-typed version: <<STUB>>/vx_v^0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vx/bin/main' {
  declare module.exports: any;
}

declare module 'vx/Gruntfile' {
  declare module.exports: any;
}

declare module 'vx/lib/config' {
  declare module.exports: any;
}

declare module 'vx/lib/Kernel' {
  declare module.exports: any;
}

declare module 'vx/lib/log' {
  declare module.exports: any;
}

declare module 'vx/lib/Plugins' {
  declare module.exports: any;
}

declare module 'vx/lib/util/str' {
  declare module.exports: any;
}

declare module 'vx/lib/VxCtx' {
  declare module.exports: any;
}

declare module 'vx/test/fixtures/projects/project_a/test.spec' {
  declare module.exports: any;
}

declare module 'vx/test/hmt' {
  declare module.exports: any;
}

declare module 'vx/test/specs/lib/config.spec' {
  declare module.exports: any;
}

declare module 'vx/test/specs/lib/Kernel.spec' {
  declare module.exports: any;
}

declare module 'vx/test/specs/lib/Plugins.spec' {
  declare module.exports: any;
}

declare module 'vx/test/specs/lib/VxCtx.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vx/bin/main.js' {
  declare module.exports: $Exports<'vx/bin/main'>;
}
declare module 'vx/Gruntfile.js' {
  declare module.exports: $Exports<'vx/Gruntfile'>;
}
declare module 'vx/index' {
  declare module.exports: $Exports<'vx'>;
}
declare module 'vx/index.js' {
  declare module.exports: $Exports<'vx'>;
}
declare module 'vx/lib/config.js' {
  declare module.exports: $Exports<'vx/lib/config'>;
}
declare module 'vx/lib/Kernel.js' {
  declare module.exports: $Exports<'vx/lib/Kernel'>;
}
declare module 'vx/lib/log.js' {
  declare module.exports: $Exports<'vx/lib/log'>;
}
declare module 'vx/lib/Plugins.js' {
  declare module.exports: $Exports<'vx/lib/Plugins'>;
}
declare module 'vx/lib/util/str.js' {
  declare module.exports: $Exports<'vx/lib/util/str'>;
}
declare module 'vx/lib/VxCtx.js' {
  declare module.exports: $Exports<'vx/lib/VxCtx'>;
}
declare module 'vx/test/fixtures/projects/project_a/test.spec.js' {
  declare module.exports: $Exports<'vx/test/fixtures/projects/project_a/test.spec'>;
}
declare module 'vx/test/hmt.js' {
  declare module.exports: $Exports<'vx/test/hmt'>;
}
declare module 'vx/test/specs/lib/config.spec.js' {
  declare module.exports: $Exports<'vx/test/specs/lib/config.spec'>;
}
declare module 'vx/test/specs/lib/Kernel.spec.js' {
  declare module.exports: $Exports<'vx/test/specs/lib/Kernel.spec'>;
}
declare module 'vx/test/specs/lib/Plugins.spec.js' {
  declare module.exports: $Exports<'vx/test/specs/lib/Plugins.spec'>;
}
declare module 'vx/test/specs/lib/VxCtx.spec.js' {
  declare module.exports: $Exports<'vx/test/specs/lib/VxCtx.spec'>;
}
