// flow-typed signature: 0c5ff7c01facb30caf24ec2f83c8ceda
// flow-typed version: <<STUB>>/wasm-loader_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wasm-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wasm-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wasm-loader/jasmine' {
  declare module.exports: any;
}

declare module 'wasm-loader/output' {
  declare module.exports: any;
}

declare module 'wasm-loader/spec/wasm-loader-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wasm-loader/index' {
  declare module.exports: $Exports<'wasm-loader'>;
}
declare module 'wasm-loader/index.js' {
  declare module.exports: $Exports<'wasm-loader'>;
}
declare module 'wasm-loader/jasmine.js' {
  declare module.exports: $Exports<'wasm-loader/jasmine'>;
}
declare module 'wasm-loader/output.js' {
  declare module.exports: $Exports<'wasm-loader/output'>;
}
declare module 'wasm-loader/spec/wasm-loader-spec.js' {
  declare module.exports: $Exports<'wasm-loader/spec/wasm-loader-spec'>;
}
